### ISSUE TITLE
Request for favicon documentation

### ISSUE THREAD

**Issue by inje** [doczjs/docz-website#25]
# Favicon Documentation Request

Hey guys, I posted a comment in [this issue here](https://github.com/pedronauck/docz/issues/39) and I'll port it over here. This is a request for documentation on how to get a favicon working.

I tried adding a favicon based on the instructions [here](https://github.com/pedronauck/docz/issues/39#issuecomment-397333205) and they didn't work for me. I found a solution that works in the meantime by adding an external link in the `doczrc.js` for the favicon.
## External favicon link
```javascript
// doczrc.js
export default {
  htmlContext: {
    favicon: 'https://s3-us-west-1.amazonaws.com/set-protocol/favicon.ico',
  },
}
```
I added this and reran `yarn dev` which showed the favicon for me. This is mostly a bandaid solution to unblock some folks who are running into the same issue.

I'm sure others are having the same issue by looking down the [list of projects using docz](https://github.com/pedronauck/docz/issues/37) who are missing favicons.

## Testing Other Repos
I tested the docz-website and island-wars repos, both of which have working deployed favicons. When running both of them locally, I didn't see working favicons.
#### docz-site
When running the docz-website locally, and saw that the favicon for the site wasn't working for me. It's confusing because the [doczrc.js leads to an `.ico` file](https://github.com/pedronauck/docz-website/blob/master/doczrc.js#L16), but the [path doesn't match up to anything inside of the public folder](https://github.com/pedronauck/docz-website/tree/master/public). The only favicon I see is a favicon in the [public/images](https://github.com/pedronauck/docz-website/tree/master/public/images) folder which is a `.png` file. When looking in the source code on docz.site, the favicon link [doesn't lead to anything](https://www.docz.site/public/favicon.ico). Would be useful to get clarification on how it works.
<img width="302" alt="screen shot 2018-08-30 at 4 22 36 am" src="https://user-images.githubusercontent.com/4149515/44848645-6b06e880-ac0c-11e8-9817-f903d6f2ac36.png">

#### island-wars
I saw [one repo in the list above](https://github.com/islands-wars/Docs) that had a working favicon, and running that locally also didn't show a favicon. [I did see a useful commit](https://github.com/islands-wars/Docs/commit/fdd9d4fa2934f132c824ccde0f10796e7b8a833b) from there that I followed and didn't get me working favicon using that method. Their site does [link to the proper favicon](https://docs.islandswars.fr/assets/favicon.ico).
<img width="279" alt="screen shot 2018-08-30 at 4 26 04 am" src="https://user-images.githubusercontent.com/4149515/44848756-d781e780-ac0c-11e8-8c92-472730a5aa2b.png">

## Production Builds
I questioned whether it was because I wasn't using a production build, so I deployed to Netlify, but also didn't see a working favicon.

**Comment by draperunner** [comment]
There have been new comments on https://github.com/pedronauck/docz/issues/39, saying that this should work:

```
export default {
  htmlContext: {
    favicon: 'public/favicon.ico'
  }
}
```

Does that work for you, @inje?

**Comment by rakannimer** [comment]
I added [a guide for this](https://github.com/doczjs/docz-website/blob/master/src/docs/documentation/customizing/add-favicon-and-metadata.mdx) to the docz site (not deployed at the time of writing).

In docz v2, you can use `react-helmet` along with `gatsby-plugin-react-helmet` to modify your favicon and/or other metadata. 

[How do I add react-helmet to my docz app](https://www.gatsbyjs.org/docs/add-page-metadata/) ?

Once you've added react-helmet you can shadow the src/wrapper.js to add metadata

so you would create a file : `src/gatsby-theme-docz/wrapper.js` and inside it : 

```js
import * as React from 'react'
import { Helmet } from 'react-helmet'

const Wrapper = ({ children }) => <React.Fragment>
	<Helmet>
		<meta charSet="utf-8" />
		<title>My Title</title>
		<link rel="icon" 
      		type="image/png" 
		    href="http://example.com/myicon.png"
		>
	</Helmet>
	{children}
</React.Fragment>
export default Wrapper
```

Closing this issue, feel free to re-open if something doesn't work.
