### ISSUE TITLE
Copyright holder and license

### ISSUE THREAD

**Issue by marcelometal** [doczjs/docz-website#35]
Hi,
Could you please add LICENSE file and put the copyright holder and license inside each file?

This way there is no chance of someone stumbling across a piece of code without being exposed to the license.

Thanks!

**Comment by rakannimer** [comment]
> Could you please add LICENSE file and put the copyright holder

Done in d812fe9cbca99458555724c44f28e90acfe6120e

> put the copyright holder and license inside each file

I'm not sure that's worth the effort for the website code.

Thanks !
