### ISSUE TITLE
document typescript

### ISSUE THREAD

**Issue by sw-yx** [doczjs/docz-website#37]
i was getting `Error: Cannot find module 'typescript'` errors until i realized that i have to manually install `typescript` myself as it is a peer dep. for some reason your example repo doesnt need typescript as an explicit dependency.

also the typescript:true flag is hard to find and should be better known. probably a standalone typescript doc is good for all these small things.

**Comment by rakannimer** [comment]
Hey ! 

Thanks for reporting this.

I added a small explainer of what you need to use TypeScript with docz. Starting from version 2 there is no need to install typescript as a dependency.

Feel free to add to the file if you feel I missed something !
