### ISSUE TITLE
Broken link: "source code of `docz-theme-default`"

### ISSUE THREAD

**Issue by Steve-Jones** [doczjs/docz-website#86]
Broken link under Examples section of "[Creating your themes](https://www.docz.site/docs/creating-your-themes#examples)" page:  

```
[source code](https://github.com/pedronauck/docz/tree/master/core/docz-theme-default) of `docz-theme-default`
```

**Comment by rakannimer** [comment]
Thanks Steve for reporting this ! Fixed 👍
